name: Run checks and deploy
on:
  push:
    branches:
      - master

jobs:
  linters_and_tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: setup docker-compose
        uses: KengoTODA/actions-setup-docker-compose@main
        with:
          version: "1.26.2"
      - name: build local
        run: docker-compose -f local.yml up --build --detach
      - name: wait for containers startup
        run: sleep 10
      - name: pylint
        run: docker exec django bash -c "pylint rcs_back"
      - name: pycodestyle
        run: docker exec django bash -c "pycodestyle rcs_back"
      - name: isort
        run: docker exec django bash -c "isort rcs_back"
      - name: run tests
        run: docker exec django bash -c "python manage.py test --settings config.settings.test --parallel --failfast"

  deploy-production:
    needs: [linters_and_tests]
    runs-on: ubuntu-latest
    steps:
      - name: deploy production with ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/restarter
            git pull
            cd ~/rcs_back
            git pull
            docker-compose -f production.yml exec -T postgres backup
            yes yes | docker image prune -a
            docker-compose -f production.yml up --detach --build --force-recreate
