name: On push checks

on: push

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: setup docker-compose
        uses: KengoTODA/actions-setup-docker-compose@main
        with:
          version: "1.26.2"
      - name: build local
        run: docker-compose -f local.yml up --build --detach
      - name: wait for containers startup
        run: sleep 10
      - name: pylint
        run: docker exec django bash -c "pylint rcs_back"
      - name: pycodestyle
        run: docker exec django bash -c "pycodestyle rcs_back"
      - name: isort
        run: docker exec django bash -c "isort rcs_back"
      - name: run tests
        run: docker exec django bash -c "python manage.py test --settings config.settings.test --parallel --failfast"
